@startuml

[*] --> ComprarBonos
note on link
 El **usuario** accede a la opción 
 de comprar bonos en el **sistema**
end note

ComprarBonos --> SeleccionarCantidad
note on link
 El usuario elige la cantidad 
 de bonos que desea comprar
end note

SeleccionarCantidad --> RealizarPago
note on link
 El sistema procesa el pago 
 de los bonos seleccionados
end note

RealizarPago --> ConfirmarCompra
note on link
 Después de verificar el 
 pago, se confirma la compra 
 de los bonos al usuario
end note

ConfirmarCompra ---> MostrarConfirmacion
note  on  link
Se añaden los fondos 
a la cuenta del usuario

El sistema muestra al 
usuario una confirmación 
de la compra de bonos
end note

RealizarPago --> NotificarFalloPago
note on link
El sistema muestra un 
mensaje de error al usuario 
y le recomienda que 
vuelva a intentar más tarde
end note

NotificarFalloPago --> [*]

MostrarConfirmacion --> [*]

@enduml
