@startuml

[*] --> ComprarBonos
note right of ComprarBonos
 El usuario accede a la opción 
 de comprar bonos en el sistema
end note

ComprarBonos --> SeleccionarCantidad
note right of SeleccionarCantidad
 El usuario elige la cantidad 
 de bonos que desea comprar
end note

SeleccionarCantidad --> RealizarPago
note right of RealizarPago
 El sistema procesa el pago 
 de los bonos seleccionados
end note

RealizarPago --> ConfirmarCompra : Pago exitoso
note right of ConfirmarCompra
 Después de verificar el 
 pago, se confirma la compra 
 de los bonos al usuario
end note

RealizarPago --> [*]
note on link
**Pago Fallido:**
Se muestra un error al usuario
y se le recomienda que vuelva
a intentar más tarde
end note

ConfirmarCompra ---> MostrarConfirmacion
note  on  link
Se añaden los fondos 
a la cuenta del usuario
end note
note right of MostrarConfirmacion
El sistema muestra al 
usuario una confirmación 
de la compra de bonos
end note

MostrarConfirmacion --> [*]
@enduml
