@startuml

[*] --> MetodoDePago
MetodoDePago --> PagarConBonos
note left of PagarConBonos
Este es el CDU de 
**PagarConBonos**
end note

MetodoDePago --> PagarConTarjeta
note on link
 El usuario escoge que 
 método de pago usar
 
 **Método de Pago: Tarjeta**
end note

PagarConTarjeta --> RealizarPago
note on link
**Datos De Pago:**
  - Número de Tarjeta
  - Nombre del Titular
  - Fecha de Caducidad
  - Código de Seguridad
end note
note right of RealizarPago
 Se efectúa el pago con el 
 TPV virtual para efectuar 
 el pago
end note

RealizarPago --> ConfirmarReserva : Pago exitoso
note left of ConfirmarReserva
 Después de verificar el 
 pago, se le envía una 
 notificación con el resumen 
 de la reserva al usuario
end note

RealizarPago --> NotificarPagoFallido : Pago fallido
note right of NotificarPagoFallido
 El sistema muestra un 
 mensaje de error al usuario, 
 quien recibe la recomendación 
 de intentarlo nuevamente más tarde
end note

NotificarPagoFallido --> [*]

ConfirmarReserva --> [*]
note on link
 Añadir reserva 
 a horarios de 
 la pista
end note

@enduml
