@startuml

[*] --> MetodoDePago
note right of MetodoDePago
 El usuario escoge que 
 método de pago usar
 
 **Método de Pago: Bono**
end note

MetodoDePago --> RealizarPago
note on link
Se verifica que el usuario
posea fondos suficientes
para realizar el pago
end note
note right of RealizarPago
Se deducen automáticamente 
los fondos correspondientes 
al valor de la reserva
end note

RealizarPago --> ConfirmarReserva : Pago exitoso
note left of ConfirmarReserva
 Después de verificar el 
 pago, se le envía una 
 notificación con el resumen 
 de la reserva al usuario
end note

RealizarPago --> NotificarPagoFallido : Pago fallido
note right of NotificarPagoFallido
 El sistema muestra un 
 mensaje de error al usuario, 
 quien recibe la recomendación 
 de intentarlo nuevamente más tarde
end note

RealizarPago --> NotificarFondosInsuficientes : Fondos insuficientes
note right of NotificarFondosInsuficientes
 El sistema muestra un 
 error al usuario indicando 
 que no dispone de suficientes fondos
end note

NotificarPagoFallido --> [*]

NotificarFondosInsuficientes --> [*]

ConfirmarReserva --> [*]
note on link
 Añadir reserva 
 a horarios de 
 la pista
end note

@enduml
