@startuml

[*] --> VerHistorialReservas
note on link
 El **usuario** accede al historial 
 de reservas
end note

VerHistorialReservas --> ConsultarReservas
note on link
 El **sistema** consulta la base de datos 
 para obtener el historial de reservas
end note

ConsultarReservas --> MostrarHistorial
note on link
Se agrega un filtro a la consulta
que varía según el tipo de **usuario**:

**Historial de Usuario**
El sistema presenta al usuario 
su historial de reservas.

**Historial de Administrador**
El sistema exhibe al administrador
el historial de reservas.
end note

MostrarHistorial --> [*]
@enduml
