@startuml Sistema de reservas

entity Reserva {
  + pista
  + fecha
  + hora
  + disponibilidad
  + idPago
}

note right of Reserva: El sistema crea, cancela y muestra el historial de reservas.

entity Usuario {
  + nombre
  + email
  + telefono
}
entity Pista {
  + número
  + horario
  + capacidad
}

entity Pago {
  + id
  + metodoPago
  + monto
}

entity Bono {
  + horasAbonadas
}

entity Factura {
  + fechaEmision
  + total
  + estado
}

entity Tarifa {
  + precioHora
}

entity Fecha {
  + dia
  + mes
  + año
}

entity Hora {
  + hora
  + minutos
}

SistemaDeReservas --- Usuario : Crea y elimina
SistemaDeReservas --- Reserva : Gestiona
Usuario --- Reserva: realiza
Reserva --- Pago: requiere
Reserva --- Pista: se lleva a cabo en
Pista --- Tarifa: se fija el precio mediante
Reserva --- Fecha
Reserva --- Hora
Pago --- Factura: Que genera 
Pago --- Bono : Puede efectuarse por

@enduml