@startuml

entity Reserva {
  + pista : 1
  + fecha: 17/05/2024
  + hora: 10:00
  + disponibilidad: sí
  + idPago: 198341
}
entity Usuario {
  + nombre: JonDoe
  + email: Jon.Doe@alumnos.unetalantico.es
  + telefono: +34 123456789
}
entity Pista {
  + número: 1 
  + horario: 8:00-20:00
  + capacidad: 4
}
entity Pago {
  + metodoDePago: Tarjeta de Crédito
  + monto: 8€
}
entity Bono {
  + horasAbonadas: 3
}
entity Factura {
  + fechaEmision: 17/05/2024 
  + total: 8€
  + estado: Pendiente
}
entity Tarifa {
  + precioHora: 8€
}


SistemaDeReservas .. Usuario :> Crea y elimina
SistemaDeReservas --- Reserva : Gestiona
Usuario --left- Reserva:> realiza
Reserva --- Pago: requiere
Reserva --- Pista: se lleva a cabo en
Pista --- Tarifa: se fija el precio mediante

Pago --- Factura: Que genera 
Pago --- Bono : < Puede efectuarse por

@enduml