@startuml
class Usuario {
  - DNI: String
  - contraseña: String
  + ingresarCredenciales(DNI: String, contraseña: String): void
}

class SistemaAutenticacion {
  + autenticar(usuario: Usuario): boolean
}

class PaginaWeb {
  + mostrarPaginaPrincipal(): void
}

class BaseDeDatos {
  - usuariosRegistrados: Set<Usuario>
  + agregarUsuario(usuario: Usuario): void
}

object Usuario1 {
  DNI= "12345678-R"
  contraseña = "contraseña123"
}

Sistema : SistemaAutenticacion
Pagina : PaginaWeb
BD : BaseDeDatos

Usuario1 --> Usuario : Crear instancia
Sistema --> Usuario1 : Recibe instancia de Usuario
Sistema --> Sistema : Autenticar(Usuario1)
Sistema --> BD : Consultar información
BD --> Sistema : Retorna información
Sistema --> Pagina : Mostrar página principal
Pagina --> Usuario1 : Mostrar interfaz

@enduml
