@startuml
|Inicio|
start
:Usuario ingresa DNI y contraseña;
if (Credenciales son válidas?) then (Sí)
  :Mostrar mensaje "Inicio de sesión exitoso";
  :Redirigir a la página principal;
  |Fin|
  stop
else (No)
  :Mostrar mensaje "Credenciales incorrectas";
  |Inicio|
  stop
endif
@enduml
