@startuml

:Inicio;
:Solicitar uso de notificaciones;
  if (Notificaciones aceptadas) then (Sí)
    :El sistema notifica al realizar la reserva;
    if (Acceso confirmado: ¿QR escaneado con éxito?) then (Sí)
      :El sistema notifica al confirmar el acceso;
      :Desarrollo de la actividad;
      while (Abandono de instalaciones confirmado: ¿QR escaneado con éxito?) is (No)
      :Finalización no confirmada;
      endwhile (Si)
        :El sistema notifica al confirmar el abandono de instalación;
    else (No)
      :No se ha desarrollado la activiad;
    endif
    :Pista disponible para uso;
  
  else (No)
    :Mostrar mensaje: ;
    :El sistema no mostrará notificaciones sobre la reserva, active notificaciones; 
  endif
  
:Fin;

@enduml