@startuml Notificar
[*] --> PermitirNotificaciones : Iniciar
PermitirNotificaciones --> PermisoAceptado : Aceptar
PermitirNotificaciones --> PermisoDenegado : Rechazar
PermisoAceptado --> NotificacionReserva : Confirmar reserva
NotificacionReserva --> NotificacionAcceso : Confirmar acceso con código
NotificacionReserva --> ActividadNoIniciada : Código QR no escaneado
NotificacionAcceso --> DesarrolloActividad
DesarrolloActividad --> NotificacionFin : Confirmar abandono de pista con código
NotificacionFin --> PistaLibre : Actividad finalizada
ActividadNoIniciada --> PistaLibre
PistaLibre --> [*]
PermisoDenegado --> [*] : Cancelar
@enduml