@startuml Notificar
[*] --> PermitirNotificaciones : Iniciar
PermitirNotificaciones --> PermisoAceptado : Aceptar
PermitirNotificaciones --> PermisoDenegado : Rechazar
PermisoAceptado --> NotificacionInicio : 10 min. antes de hora inicio
NotificacionInicio --> InicioActividad : Confirmar Actividad
InicioActividad --> DesarrolloActividad
DesarrolloActividad --> NotificacionFin : 3 min. antes de hora fin
NotificacionFin --> XXComprobacionPistaLibreXX : Confirmar Fin
XXComprobacionPistaLibreXX --> PistaLibre
NotificacionInicio --> ActividadNoIniciada : Actividad No Confirmada
ActividadNoIniciada --> PistaLibre
PistaLibre --> [*]
PermisoDenegado --> [*] : Cancelar
@enduml