@startuml Notificar

object Usuario {
  nombreUsuario : juancarlos@alumnos.uneatlantico.es
}
object Reserva {
  horaInicio : 12:00
  horaFin : 13:00
  dia : 12/12/2023
  pista : 1
}

object NotificacionReserva {
  Hora : Reserva.horaReserva
  Objetivo : Recordatorio reserva
}

object NotificacionAcceso {
  Hora : Reserva.horaAccesoAPista
  Objetivo : Notificar acceso registrado con éxito
}

object NotificacionFin {
  Hora : Reserva.horaFinActividad
  Objetivo : Notificar abandono de instalacciones registrado con éxito
  EstadoPista : Libre
}

Usuario --> Reserva : PermitirNotificaciones()
Reserva --> NotificacionReserva : ReservaConfirmada()
NotificacionReserva --> NotificacionAcceso : EscanearCódigoEntrada()
NotificacionAcceso --> NotificacionFin : EscanearCódigodigoSalida()
NotificacionFin --> Reserva : NuevaReserva()
@enduml