@startuml
Entity SistemaDeReservas
Entity Pistas
Entity Padel
Entity Polideportivo
Entity Voleibol
Entity Calendario
Entity Usuario
Entity Pagos
Entity Factura
Entity Tarifas
Entity Disponivilidad
Entity Reserva
Entity CancelarReserva
Entity Fecha
Entity Horas


SistemaDeReservas --- Usuario: Tiene
Usuario --- Reserva: Hace
Reserva -L- Calendario: tiene
Usuario -R- Pagos: Realiza
Pagos --- Factura: Que genera 
Factura --- Usuario: Que se le entrega
Reserva --- Pistas: Se realiza en
Reserva -L- CancelarReserva: Se puede cancelar
Pistas--- Padel
Pistas--- Polideportivo
Pistas--- Voleibol
Pistas -R- Tarifas: Tiene
Voleibol --- Disponivilidad: Tiene
Polideportivo --- Disponivilidad: Tiene
Padel --- Disponivilidad: Tiene
Disponivilidad--- Calendario: Tiene
Calendario --- Fecha
Calendario --- Horas
@enduml