@startuml
[*] --> Inicio
Inicio --> PaginaPrincipal
note on link
Usuario accede a la aplicación
end note
PaginaPrincipal --> EditarHorarios
note on link
Usuario selecciona "Editar horarios de pistas"
end note
EditarHorarios --> ConfirmarEdicion
note on link
Aqui el usuario ha de seleccionar una pista,
 y un nuevo horario de apertura
end note
ConfirmarEdicion --> Error
note on link
Error de permisos o de conexión
end note
Error --> EditarHorarios
note on link
Volver a intentar
end note
ConfirmarEdicion --> NotificarUsuarios
note on link
Confirmación de la modificación
end note
NotificarUsuarios --> [*] 
note on link
Verificar si alguna reserva ha sido afectada
por esta modificación, notificar a los usuarios
end note

@enduml
