@startuml
[*] -->  EditarHorarios
note on link
El **Administrador** edita el horario 
de la Pista
end note
EditarHorarios --> ConfirmarEdicion
note on link
El **sistema** confirma 
la edicióndel horario 
de la Pista
end note

EditarHorarios -[#red]> [*]
note on link
El **sistema** notifica al 
**Administrador** que se 
ha producido un Error
end note
ConfirmarEdicion ---> NotificarUsuarios
note on link
El **sistema** notifica a los usuarios
que se ha producido un cambio en el horario
de la Pista
end note
NotificarUsuarios --> [*] 
note on link
El **sistema** verifica que el cambio
de horario genera conflictos con las 
reservas de los **usuarios**, si es así,
notifica a los **usuarios**
end note

@enduml
