@startuml 
[*] --> UsuarioSolicitaPista
UsuarioSolicitaPista -d-> SistemaMuestraPista
note on link
    El usuario solicita una pista
end note
SistemaMuestraPista -d-> UsuarioIntroduceModificaciones
note on link
    El sistema muestra la pista
end note
SistemaMuestraPista -d-> Error
note on link
    La pista no se puede mostrar
end note
UsuarioIntroduceModificaciones -d-> SistemaModificaPista
note on link
    El usuario introduce las 
    modificaciones necesarias
end note
SistemaModificaPista -d-> SistemaMuestraPistaModificada
note on link
    El sistema modifica 
    y muestra la pista
end note
SistemaModificaPista -r-> Error
note on link
    El sistema no puede modificar la pista
end note
Error -d-> [*]
note on link
    **Fin**
end note
SistemaMuestraPistaModificada -d-> [*]
note on link
    **Fin**
end note

@enduml