@startuml 
[*] --> UsuarioSolicitaMenuCrearPista
UsuarioSolicitaMenuCrearPista ---> SistemaMuestraMenuCrearPista
note on link
    El **administrador** solicita acceder 
    al menu de crear 
    pista
end note
SistemaMuestraMenuCrearPista -r-> UsuarioIntroduceDatosPista
note on link
    El **sistema** muestra
    el menu  para introducir
    los datos de la pista
end note
UsuarioIntroduceDatosPista -d-> UsuarioSolicitaCrearPista 
note on link
    El **administrador** introduce los datos
    de la pista
end note
UsuarioSolicitaCrearPista -r-> SistemaCreaPista
note on link
    El **administrador** solicita 
    crear la pista
end note
SistemaCreaPista --> SistemaMuestraNuevaPista
note on link
    El **sistema** 
    crea y muestra
    la nueva pista
end note
SistemaCreaPista -[#red]->  [*]
note on link
    El **sistema** muestra un error
    al crear la pista
end note

SistemaMuestraNuevaPista --> [*]

@enduml 
