@startuml 
[*] -r-> UsuarioSolicitaMenuCrearPista
UsuarioSolicitaMenuCrearPista -d-> SistemaMuestraMenuCrearPista
note on link
    El usuario solicita acceder 
    al menu de crear 
    pista
end note
SistemaMuestraMenuCrearPista -r-> UsuarioIntroduceDatosPista
note on link
    El sistema muestra
    el menu  para introducir
    los datos de la pista
end note
UsuarioIntroduceDatosPista -d-> UsuarioSolicitaCrearPista 
note on link
    El usuario introduce los datos
    de la pista
end note
UsuarioSolicitaCrearPista -r-> SistemaCreaPista
note on link
    El usuario solicita 
    crear la pista
end note
SistemaCreaPista -d-> SistemaMuestraNuevaPista
note on link
    El sistema 
    crea y muestra
    la nueva pista
end note
SistemaCreaPista -d-> Error
note on link
    El sistema muestra un error
    al crear la pista
end note
Error-d-> [*]
note on link
    **Fin**
end note
SistemaMuestraNuevaPista -d-> [*]
note on link
    **Fin**
end note
@enduml 
