@startuml
[*] --> Inicio
Inicio --> PaginaPrincipal
note on link
    Usuario accede a la aplicación
end note
PaginaPrincipal --> Reservas
note on link
Usuario selecciona "ver estados de pistas"
end note
Reservas --> [*]
note on link
Usuario visualiza las reservas"
end note
@enduml
