@startuml 
[*] --> UsuarioSolicitaPistas
UsuarioSolicitaPistas -d-> SistemaMuestraPistas
note on link
    El usuario solicita las pistas al sistema
end note
SistemaMuestraPistas -d-> UsuarioDecideProximaOperacion
note on link
    El sistema muestra las pistas al usuario
    para que este decida que hacer a continuacion
end note
UsuarioDecideProximaOperacion --> UsuarioSolicitaPistas
note on link
    **Recarga**
end note
SistemaMuestraPistas -d-> Error
note on link
    El sistema no puede mostrar
    las pistas al usuario
end note
Error -d-> [*]
note on link
    **Fin**
end note
UsuarioDecideProximaOperacion -d-> [*]
note on link
    El usuario decidira que hacer a continuacion
end note

@enduml