@startuml
object "Formulario de Creación de Cuenta" as formulario {
  DNI: string
  Código postal: Int
  Nombre Completo: string
  Correo: string
  Número de teléfono: Int
}

object "Base de Datos de Usuarios" as base_de_datos {
  -- Almacena información de usuarios --
}

object "Servidor Web" as servidor {
   Procesa las solicitudes 
}

formulario --> servidor : envía información
servidor --> base_de_datos : almacena información
@enduml
