@startuml
start
:Acceder a la aplicación;
:Seleccionar "ver estados de las reservas";
if (Validar usuario) then (admin)
  :Elegir pista;
  :Cambiar franja horaria de apertura;
  :Cancelar reservas de pista si no se encuentra disponible en nuevo horario;
  :Notificar a los usuarios afectados;
  :Confirmar edición de pista;
else (user)
  :No se muestra la opción;
endif

stop
@enduml
