@startuml
object Usuario
object Aplicacion
object Horarios
object Reservas
object Confirmacion
object Error

Usuario --> Aplicacion : Acceder
Usuario --> Aplicacion : Editar Horarios
Usuario --> Horarios : Realizar cambios
Usuario --> Horarios : Confirmar cambios
Horarios --> Confirmacion : Confirmar cambios
Confirmacion --> Aplicacion : Éxito
Confirmacion --> Error : Fallo
Error --> Horarios : Volver a editar
Usuario --> Aplicacion : Ver reservas
Aplicacion --> Reservas : Visualizar
@enduml
