@startuml Diagrama objetos gestionar admin

interface User {
  - userInfo: UserInfo

  + getUserInfo(): UserInfo
}

interface Bonus {
  - bonusInfo: BonusInfo

  + getBonusInfo(): BonusInfo
}

class Gestiones {
  - isAuthenticated: boolean
  - adminUsers: GestionarUsuarios
  - adminBonus: GestionarBonos
  
  + goToAdminUsers(): void
  + goToAdminBonus(): void
}

class GestionarUsuarios implements User {
  - users: Object<User>
  
  + showUsers(): void
  + addUser(user: User): void
  + editUser(user: User): void
  + deactivateUser(user: User): void
  + deleteUser(user: User): void
}

class GestionarBonos implements Bonus {
  - bonuses: Object<Bonus>
  
  + showBonuses(): void
  + createBonus(bonus: Bonus): void
  + editBonus(bonus: Bonus): void
}

Gestiones --> GestionarUsuarios
Gestiones --> GestionarBonos

@enduml
