@startuml
title Actualizar Bonos (Admin)



[*] --> Inicio
note left of Inicio
 El administrador accede desde la página de inicio
endnote

Inicio --> ListaDeBonos : Cargar Bonos

ListaDeBonos --> EditarBonos : Seleccionar Bono
note right of ListaDeBonos 
 El administrador accede a la opción 
 de ver la lista de Bonos
endnote

EditarBonos --> BonosActualizados : Confirmar Cambios
note left of EditarBonos 
 El administrador accede a la opción 
 de editar los bonos creados anteriormente
endnote


BonosActualizados --> ListaDeBonos : Actualizar Otro
BonosActualizados --> [*] : Finalizar

@enduml
