@startuml ReservasDePistasDePadel

left to right direction
actor User as U
actor Admin as A


package Reserva{

    usecase "Realizar Reserva" as UC1
    usecase "Cancelar Reserva" as UC2
    usecase "Ver Historial de Reservas" as UC9
    usecase "Ver Reservas" as UC5
    usecase "Gestionar Bonos" as UC11
}

package Pistas {

    usecase "Administrar Horarios de Pistas" as UC10
    usecase "Administrar Pistas" as UC15
    usecase "Ver Disponibilidad de Pistas" as UC3
}

package Pagos{

    usecase "Pagar Reserva" as UC13
    usecase "Pagar Bonos" as UC14
    usecase "Administar Pagos" as UC12

}

package Notificaciones{

   usecase "Recibir Notificaciones de Reservas" as UC8
   usecase "Recibir Notificaciones de Bonos" as UC4
   usecase "Recibir Notificaciones de Pagos" as UC16
   usecase "Recibir Notificaciones de Pistas" as UC17
   usecase "Gestionar Notificaciones" as UC7
 
}


A-up-> Reserva
A -up-> Pistas

A --> UC12
A -down->UC7

U --> UC1
U --> UC2
U -left-> UC3
U --> UC9
U --> UC13
U --> UC14

U-->UC8
U-->UC4
U-->UC16
U-->UC17

@enduml
