@startuml
start
:Usuario solicita cancelación;
:Verificar tiempo antes de la reserva;
if ("Más de 48 horas antes?") then (sí)
  :Cancelar reserva;
  :Notificar cancelación al usuario;
  :Reembolso al usuario (a cartera de aplicación);
stop
else (no)
if(¿Está lloviendo el dia de la reserva?) then (si)
:Cancelar reserva por mal tiempo;
:Notificar cancelación al usuario;
:Reembolso al usuario (a cartera de aplicación);
else (no)
  :Denegar cancelación;
  :Notificar motivo al usuario;
endif
stop
@enduml
