@startuml
object Usuario {
  nombre: String
}

object Reserva {
  fechaHora: DateTime
  estado: String
  climaActual: String
}

object SistemaDeCancelacion {
  tiempoMin: Int = 48
  lluviaDiaReserva: Bool = false;
}

Usuario --> Reserva : realiza
Reserva --> SistemaDeCancelacion : verifica 
@enduml
