@startuml
state Activa {
}
state Cancelada {
}
state "No se puede cancelar" as NoPuedeCancelar {
}

[*] --> Activa
Activa --> Cancelada : Cancelación exitosa\n(>48 horas antes)
Activa --> CanceladaLluvia : Mal tiempo
Activa --> NoPuedeCancelar : Intento de cancelación\n(<48 horas antes)
NoPuedeCancelar --> Activa : Mantener reserva
Cancelada --> [*]
CanceladaLluvia --> [*]
Activa --> [*] : Continua sin cancelación
NoPuedeCancelar --> [*] : Continua sin cancelación
@enduml
