@startuml
[*] -> NoHayCanchas : Inicio

state NoHayCanchas {
    [*] --> AñadirPista
    AñadirPista --> HayCanchas : Pista añadida
}

state HayCanchas {
    [*] --> MostrarOpciones 
    MostrarOpciones --> OpcionAñadir : Selecciona Añadir
    MostrarOpciones --> OpcionModificar : Selecciona Modificar
    MostrarOpciones --> OpcionEliminar : Selecciona Eliminar
    OpcionEliminar --> OpcionEliminar: Selecciona Cancha Inexistente
    OpcionModificar --> OpcionModificar: Selecciona Cancha Inexistente
    OpcionAñadir --> SolicitarCanchas: Cancha Añadida
    OpcionModificar --> SolicitarCanchas: Cancha Modificada
    OpcionEliminar --> SolicitarCanchas: Cancha Eliminada
    SolicitarCanchas -> HayCanchas : Hay Canchas
    SolicitarCanchas --> NoHayCanchas : No Hay Canchas
}

@enduml
