@startuml

object Administrador{
    nombreUsuario: admin@uneatlantico.es
}
object GestorCanchas{
    metodos:{añadir, modificar, eliminar}
}
object Cancha{
    numeroDeCancha: 1
    codigoDePuerta: 739128498
}

Administrador --> GestorCanchas: RealizaOperaciones()
GestorCanchas --> Cancha: OperacionesCancha()
Cancha --> GestorCanchas: NuevaOperacion()

@enduml