@startuml
:Inicio;

repeat

:Administrador solicita canchas;

  if (¿Hay canchas disponibles?) then (Sí)
    :Ofrecer opciones\n(Añadir/Modificar/Eliminar canchas);

    if (Selecciona Añadir) then (Añadir)
      :El Administrador añade una cancha;

    else if (Selecciona Modificar) then (Modificar)
      
      repeat
        :El Administrador elige\nuna cancha para modificar;
      repeat while (Cancha existe)

      if (Confirmación de modificación) then (Sí)
        :El Administrador modifica la cancha;

      else (No)
        :El Administrador cancela la modificación;
      endif

    else if (Selecciona Eliminar) then (Eliminar)

      repeat
        :El Administrador elige\nuna cancha para eliminar;
      repeat while (Cancha existe)

      if (Confirmación de eliminación) then (Sí)
        :El Administrador elimina la cancha;

      else (No)
        :El Administrador cancela la eliminación;
      endif
    endif

  else (No)
    :Mostrar mensaje\n(No hay canchas disponibles);
    :El Administrador añade una nueva cancha;
  endif
  
repeat while (continuar)

:Volver a solicitar canchas;
@enduml
