
@startuml Sistema de gestion
package "Modelo de Dominio: Reserva de Pistas" {

entity "Pista" as Pista 
entity "Reservas" as Reservas
entity "Cancelaciones" as Cancels
entity "Usuario" as Usuario 
entity "Uneatlantico" as Universidad 
entity "App Móvil" as App 
entity "Web Universidad" as Web 
entity "Sistema de reserva" as SG 
entity "Interfaz de Usuario" as UI 
entity "Proceso de Pago" as Pago 
entity "Notificaciones" as Notif

Reservas --> Pista : "solicita"
Reservas --> Usuario : "realizada por"
Cancels <-- Reservas : "gestiona"
Universidad --> Pista : "contiene"
App --> UI : "muestra"
App --> Reservas : "gestiona"
App --> Notif : "envía"
App --> Usuario : "gestiona"
Pago <-- Reservas : "requiere"
Web --> SG : "contiene"
SG --> App : "implementa"

}

@enduml