@startuml Sistema de gestion
package "Modelo de Dominio: Reserva de Pistas" {

entity "Pista" as Pista {
    + Libre
    + Ocupada
    + En mantenimiento
}
entity "Reservas" as Reservas {
    + Fecha 
    + Hora
    + Confirmación 
    + Cancelación 
    + Pago
    + Máximo una semana de antelación
}
entity "Cancelaciones" as Cancels
entity "Usuario" as Usuario {
    + DNI
    + Tarjeta
    + Nombre
    + Correo de la Universidad
    + Usuario administrativo
}
entity "Uneatlantico" as Universidad 
entity "App Móvil" as App {
    + Usuario
    + Tus reservas
    + Configuración
    + Canchas
}
entity "Web Universidad" as Web 
entity "Sistema de reserva" as SG 
entity "Interfaz de Usuario" as UI {
    + Tarjeta
    + Configuración
}
entity "Proceso de Pago" as Pago {
    + Tarifa: 15 euros/1.5 horas
    + Tarifa: 8 euros/1 hora
}
entity "Notificaciones" as Notif {
    + Inicio de reserva
    + Fin de resrva
}

Reservas --> Pista : "solicita"
Reservas --> Usuario : "realizada por"
Cancels <-- Reservas : "gestiona"
Universidad --> Pista : "contiene"
App --> UI : "muestra"
App --> Reservas : "gestiona"
App --> Notif : "envía"
App --> Usuario : "gestiona"
Pago <-- Reservas : "requiere"
Web --> SG : "contiene"
SG --> App : "implementa"

}

@enduml