@startuml

[*] --> VerNotificaciones
note right of VerNotificaciones
 El usuario accede a la opción 
 de ver sus notificaciones
end note

VerNotificaciones --> SeleccionarNotificacion
note right of SeleccionarNotificacion
 El usuario selecciona la notificación 
 que desea leer
end note

SeleccionarNotificacion --> LeerNotificacion
note right of LeerNotificacion
 El sistema muestra el contenido 
 de la notificación seleccionada
end note

LeerNotificacion --> ConfirmarLectura : Leer
note right of ConfirmarLectura
 El usuario confirma que ha leído 
 la notificación
end note

ConfirmarLectura --> MostrarConfirmacion : Confirmación de lectura
note right of MostrarConfirmacion
 El sistema muestra una confirmación 
 al usuario de que la notificación 
 ha sido marcada como leída
end note

MostrarConfirmacion --> [*]

@enduml
