@startuml Reserva 

object Reserva {
  +Nombre: Jon Doe
  +fechaReserva: 01/01/2024
  +horaInicio: 11:00
  +horaFin: 12:00
}

object Pista {
  +numero: 1
}

object EstadoReserva {

  +Estado: CANCELADA
}

object EstadoPista {
  +estado: OCUPADA
}

Reserva <-down-> Pista : Realiza
Reserva <-up-> EstadoReserva : Tiene estado
Pista  <-->  EstadoPista : Tiene estado

@enduml
