@startuml
title Borrar Usuario

[*] --> BorrarUsuario
note right on link
 El **usuario/administrador** accede a la opción 
 de eliminar un usuario del sistema

 Dependiendo de su rol: 
 - **Usuario**: solo se puede borrar a el mismo 
 - **Administrador**: puede eliminar cualquier usuario
end note

BorrarUsuario --> VerificarUsuario
note right on link
 El **sistema** verifica la identidad 
 del usuario/administrador
end note

VerificarUsuario --> ConfirmarBorrado

ConfirmarBorrado --> BorrarCuenta
note right on link
 El **sistema** procede a eliminar la cuenta 
 del usuario seleccionado
end note

BorrarCuenta --> [*] 

@enduml
