@startuml

left to right direction

actor User as U
actor Admin as A


package Reserva{

    usecase "Realizar Reserva" as UC1
    usecase "Cancelar Reserva" as UC2
    usecase "Ver Historial de Reservas" as UC3
    usecase "Crear Bonos" as UC4
    usecase "Leer Bonos" as UC5
    usecase "Actualizar  Bonos" as UC6
    usecase "Borrar Bonos" as UC7
}

U --> UC1
U -->UC2
U -->UC3

A-->UC3
A --> UC4
A --> UC5
A --> UC6
A --> UC7





@enduml