@startuml
title Actualizar Bonos (Admin)

[*] --> Inicio
Inicio --> ListaDeBonos : Cargar Bonos
ListaDeBonos --> EditarBonos : Seleccionar Bono
EditarBonos --> BonosActualizados : Confirmar Cambios
BonosActualizados --> ListaDeBonos : Actualizar Otro
BonosActualizados --> [*] : Finalizar

@enduml
