@startuml
title Borrar Bonos (Admin)

[*] --> Inicio
Inicio --> ListaDeBonos : Cargar Bonos
ListaDeBonos --> ConfirmarBorrado : Seleccionar Bono
ConfirmarBorrado --> BonoBorrado
BonoBorrado --> ListaDeBonos : Borrar Otro
BonoBorrado --> [*] : Finalizar

@enduml
