@startuml
title Cancelar Reserva

[*] --> SeleccionDeReserva
note on link
 El **usuario** selecciona la 
 reserva que desea cancelar
end note

SeleccionDeReserva --> VerificarCondiciones
note on link
 El **sistema** verifica si la cancelación cumple con las políticas:

 - No se permite cancelar el mismo día, 
   a menos que el clima no sea óptimo.

 - Se permite la cancelación con al menos 
   24 horas de anticipación.
end note

VerificarCondiciones ---> NoSePuedeCancelar 
note on link
 El **sistema** informa al **usuario** 
 que no se puede cancelar

end note

VerificarCondiciones --> ConfirmacionCancelar
note on link
El **sistema** le permite al 
**usuario** realizar la cancelación
end note

ConfirmacionCancelar --> ReservaCancelada
note on link
El **sistema** confirma al **usuario**
que la reserva ha sido cancelada
end note


NoSePuedeCancelar ---> [*] 
ReservaCancelada ---> [*]

@enduml
